name: Checking Tests

on: 
    pull_request:
        branches:
            - develop

jobs:
    cypress-run:
        name: Checking Cypress Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                build: npm run build
                start: npm run start
                component: true 
                run: npm run test-component
                
                
                
