name: Deploy to Render

on:
  pull_request:
    branches:
      - main 

jobs: 
  ci:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
